---
- name: apply common configuration to all nodes
  hosts: 127.0.0.1

  vars:
    wildfly:
      inst1:
        modulo: api
        url_modulo:
          - https://jdbc.postgresql.org/download/postgresql-42.1.4.jar
      inst2:
        modulo: processor
        url_modulo:
          - https://jdbc.postgresql.org/download/postgresql-42.1.4.jar

  tasks:

    - name: Teste
      # bug-v2.3
      # include: files.yml instancia="{{ item.value.url_modulo }}" folder_module="/opt/teste/{{ item.value.modulo }}/modules"
      include_tasks: files.yml instancia="{{ item.value.url_modulo }}" folder_module="/opt/teste/{{ item.value.modulo }}/modules"
      when: item.value.modulo is defined
      with_dict: "{{ wildfly }}"
